### ISSUE TITLE
@Ahmadkhan Job's

### ISSUE THREAD

**Issue by raoasifraza11** [interpreter-zone/ani-motors#11]
### Todo jobs

- [x] Login, singup form and grap data and sent it to email
- [x] Email Templates
- [x] Menu
- [x] Lang/en/app put all key values
- [ ] Terms and condition
- [ ] Home page content writing
- [x] Home page social links
- [x] Gmail account
- [x] Social Pages
- [ ] Logo replacement

**Comment by Ahmadkhan12345566** [comment]
ok

**Comment by Ahmadkhan12345566** [comment]
admin panel clean and fixed broken links

**Comment by raoasifraza11** [comment]
Okay

**Comment by Ahmadkhan12345566** [comment]
Lang/en/app put all key values done

**Comment by Ahmadkhan12345566** [comment]
gmail account, not available  with (animotor OR animotors )
kindly suggest what to do ... @raoasifraza11

**Comment by raoasifraza11** [comment]
append with any number

**Comment by Ahmadkhan12345566** [comment]
ok

**Comment by Ahmadkhan12345566** [comment]
animotor786@gmail.com

**Comment by raoasifraza11** [comment]
Done 👍 Gmail. Thanks

**Comment by raoasifraza11** [comment]
@Ahmadkhan12345566 Kindly see person for content writing....

**Comment by Ahmadkhan12345566** [comment]
logo fix ho ky ay?

**Comment by raoasifraza11** [comment]
In a pipeline

**Comment by Ahmadkhan12345566** [comment]
ok 
kindly review the name of form newly created ...
